### ISSUE TITLE
A criação da aplicação Python está um pouco complexa de entender.

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-sa-brazil/workshop-openshift#2]

**Comment by rafaeltuelho** [comment]
Não entendi?!

Eu acho que ela está bem simples! Alguem poderia validar e encerrar essa issue?

**Comment by luszczynski** [comment]
@rafaeltuelho, não entendi. Vc que abriu essa issue.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
