### ISSUE TITLE
[Parte 1 - Linux Containers] Explicar o uso do CRI-O e outras ferramentas como buildah, podman, etc

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#22]
Na parte "Afinal, o que são containers?" devemos adicionar e explicar o CRI-O e também outras ferramentas como buildah, podman, etc

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
