### ISSUE TITLE
[Lab 1.3 - Compartilhar] Problemas ao copiar e colar os códigos fontes

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#23]
Se o usuário seleciona o texto e depois copia para o clipboard, caracteres estranhos estão sendo também copiados. 
Isso não acontece quando o usuário clica no ícone de copiar que fica no lateral direita de cada código fonte.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
