### ISSUE TITLE
[2.1.5 - Source to Image (S2I)] Erro de build durante o source-to-image

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#25]
Necessário adicionar  os comandos abaixo para corrigir caso aconteça algum erro de build no source-to-image. Adicione depois de "Caso você encontre o erro abaixo durante o build:"

yum remove subscription-manager-rhsm-certificates
yum install -y http://mirror.centos.org/centos/7/os/x86_64/Packages/python-rhsm-certificates-1.19.10-1.el7_4.x86_64.rpm

**Comment by luszczynski** [comment]
Parece que teve alguma alteração no comando acima, e o melhor modo de corrigir esse problema é executando:
```bash
rm /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt
```

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
