### ISSUE TITLE
[2.1.5 - Source to Image (S2I)] Acompanhar o balanceamento de carga na hora de escalar os pods

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#26]
Na parte de "Escalar para 4 PODs" seria interessante colocar o comando de while para acompanhar o balanceamento automático.

while [ true ]; do curl http://app-abc.apps.example.com/; sleep 0.5; echo; done

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
