### ISSUE TITLE
[2.1.7 - Binary Deployment] Adicionar comando de limpeza

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#27]
Como esse lab não é utilizado para outras coisas, seria interessante adicionar um comando de limpeza dos recursos criados. Isso ajuda a manter os labs organizados e também evita confusão dos alunos.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
