### ISSUE TITLE
[2.1.15 - Rollback] Adicionar alteração no código-fonte e melhorias na explicação

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#28]
Adicionar uma alteração na versão do código fonte (como por exemplo: v3.0). Dessa forma fica mais claro que o rollback de fato aconteceu.

Além disso, adicionar explicação dos botões

* Replica Count  and selector
* Deployment strategy
* Deployment trigger

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
