### ISSUE TITLE
[2.1.16 - Idle] Idle não funciona

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#29]
Descobri porque o idle não está funcionando corretamente. O pod entra em idle, mas não sai quando clicamos no link da aplicação.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
