### ISSUE TITLE
[2.1.18 - ConfigMap e Secrets] Adicionar exemplo de secret

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#30]
Nesse lab só existe exemplo de configmap. Adicionar exemplo de secret juntamente com explicação.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
