### ISSUE TITLE
[2.2.1 Canary Release] Trocar as referencia de php para ocp

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#32]
Durante alterações que foram feitas no lap há um tempo atrás, ficaram algumas referencias ao recurso antigo chamado workshop-php. Todos os labs usam workshop-ocp. Então seria necessário trocar tudo que é php por ocp.
Um ctrl f na página já mostra que tem muita referencia ao php. Além disso, precisamos trocar os gifs. Mas acredito que essa última parte das imagens pode ser feito depois

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
