### ISSUE TITLE
[2.2.1 Canary Release] Alteração do comando oc new-app

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#33]
Nos comandos que seguem logo após o texto "Crie uma nova app usando a versão do Branch 3.0 que acabamos de criar usando o comando", alterar o comando `oc new-app` conforme abaixo:

```
oc new-app --name=workshop-ocp-v3 https://github.com/<username>/workshop-openshift.git#v3.0
 --strategy=source
```

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
