### ISSUE TITLE
Test Drive de um dia

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#34]
A ideia dessa issue, é discutir como podemos simplificar o test drive para que seja executado somente em um único dia. Acho que o primeiro passo é ver qual lab tem dependencias com outros labs.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
