### ISSUE TITLE
[Parte 1 - Linux Containers] Remover o # do inicio dos comandos

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#36]
O # é utilizado nos comandos para explicar para o usuário que o comando deve ser executado como root. Nos workshops tem havido muita confusão dos usuários. Acho que devemo remover esse simbolo de todos os labs da parte 1.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
