### ISSUE TITLE
[1.1.7 - Executando imagem do Wordpress] Erro na exportação da porta

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#38]
Trocar a porta do comando do wordpress.

Antes
`docker run --rm -p 80:8080 wordpress` 

Depois:
`docker run --rm -p 80:80 wordpress`

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
