### ISSUE TITLE
[1.3.2 - Publicar Imagens no Registry] Adicionar screenshots com resultados dos comandos 

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#39]
Os alunos tem perguntado com frequencia qual deveria ser o resultado dos comandos dessa parte do lab. Adicionar screenshots ajudaria a diminuir essas perguntas.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
