### ISSUE TITLE
Substituir a CLI por operações na Console UI (onde for possível)

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-sa-brazil/workshop-openshift#4]
Evitar usar OC para funções que já existem na interface gráfica ou, primeiramente executa-se tudo pela interface gráfica e depois demonstra usando oc.

**Comment by luszczynski** [comment]
Então, só não acho que devemos substituir a CLI e sim deixá-la como uma segunda opção. Tem muito cliente que gosta dela.
