### ISSUE TITLE
[2.1.6 - Usando Dockerfile] Problemas ao copiar e colar o código fonte

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#40]
Caracteres estranhos estão aparecendo no Dockerfile quando ele é copiado e colado usando o mouse.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
