### ISSUE TITLE
Trocar cluster up pelo minishift

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#41]
Agora na última versão do minishift, é possível utilizá-lo na nuvem. Sugiro trocar o cluster up pelo minishift.
https://medium.com/@kamesh_sampath/identify-yourself-on-minishift-c85f5bf8ba7d

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
