### ISSUE TITLE
[2.1.12 - Pipeline] Arrumar erro no carregamento da imagem

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#44]
Logo no inicio do lab, existe uma imagem que não é carregada. Precisamos arrumar isso.

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
