### ISSUE TITLE
[2.1.1 - Acesso ao ambiente] Throubleshooting

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#48]
Adicionar o seguinte comando para limpeza total do ambiente em casos de necessidade de reinstalação do oc cluster up

for m in $(mount | grep openshift | awk '{print $3}'); do umount $m; done

**Comment by davivcgarcia** [comment]
Estou fechando `Issues` antigas sem atividade como parte da faxina no repositório. Caso precisem dela aberta, fiquem a vontade de reabrir.
