### ISSUE TITLE
Colocar instruções para criar rotas

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-sa-brazil/workshop-openshift#5]
em alguns casos (`oc new-app`) a rota é criada automaticamente e em alguns não é criada. Creio que devamos adicionar um `oc expose` explicito após o `oc new-app`

**Comment by luszczynski** [comment]
@rafaeltuelho seria legal referenciar aqui em qual parte do workshop vc viu isso.

**Comment by rafaeltuelho** [comment]
@luszczynski infelizmente não me recordo. Tem que observar nos labs de criação de apps com `oc new-app ...`

**Comment by rafaeltuelho** [comment]
acho que já foi adicionado
