### ISSUE TITLE
Problema no Lab 1.1 Configuracao certificado ssl registry docker

### ISSUE THREAD

**Issue by glaucioguerra** [redhat-sa-brazil/workshop-openshift#55]
Ao tentar adicionar o pacote do passo 1.1 (lab docker) tenho o seguinte erro:

```
[root@localhost ~]# yum install http://mirror.centos.org/centos/7/os/x86_64/Packages/python-rhsm-certificates-1.19.10-1.el7_4.x86_64.rpm
Loaded plugins: fastestmirror
python-rhsm-certificates-1.19.10-1.el7_4.x86_64.rpm                                                                                      |  41 kB  00:00:00     
Examining /var/tmp/yum-root-fRHU6x/python-rhsm-certificates-1.19.10-1.el7_4.x86_64.rpm: python-rhsm-certificates-1.19.10-1.el7_4.x86_64
Cannot install package python-rhsm-certificates-1.19.10-1.el7_4.x86_64. It is obsoleted by installed package subscription-manager-rhsm-certificates-1.24.13-3.el7.centos.x86_64
Error: Nothing to do
```
Tentei instalar o pacote equivalente, porem o problema de ssl continua quando executo o docker pull do repo da red hat:

```
[root@localhost ~]# docker pull registry.access.redhat.com/rhel-atomic
Using default tag: latest
Trying to pull repository registry.access.redhat.com/rhel-atomic ... 
open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
```

**Comment by davivcgarcia** [comment]
Olá Glauco, obrigado pelo feedback! Algumas perguntas:
1. Qual a versão (v3.6 ou v3.11) do material você está usando? 
2. Os pacotes do CentOS 7 estão atualizados (`yum update -y`)?
3. Qual a saída dos comandos `tree /etc/docker/certs.d/` e `tree /etc/containers/certs.d/`?

**Comment by glaucioguerra** [comment]
Opa, por nada! Vamos la:
1. Versao 3.11 (primary version no gitbook)
2. Vou executar, a box tem 20 dias aprox. de atualizacao
3.
Saida 1:
```
[root@localhost ~]# tree /etc/docker/certs.d/
/etc/docker/certs.d/
├── redhat.com
│   └── redhat-ca.crt -> /etc/rhsm/ca/redhat-uep.pem
├── redhat.io
│   └── redhat-ca.crt -> /etc/rhsm/ca/redhat-uep.pem
└── registry.access.redhat.com
    └── redhat-ca.crt -> /etc/rhsm/ca/redhat-uep.pem
```
Saida 2:
```
[root@localhost ~]# tree /etc/containers/certs.d/
/etc/containers/certs.d/ [error opening dir]

0 directories, 0 files
```
So uma observacao, o path do certificado aponta para um link simbolico quebrado:
```
[root@localhost registry.access.redhat.com]# ls -lha
total 0
drwxr-xr-x. 2 root root 27 Oct 30 21:30 .
drwxr-xr-x. 5 root root 75 Oct 30 21:30 ..
lrwxrwxrwx. 1 root root 27 Oct 30 21:30 redhat-ca.crt -> /etc/rhsm/ca/redhat-uep.pem
```
```
[root@localhost registry.access.redhat.com]# ls -lha /etc/rhsm/ca/redhat-uep.pem
ls: cannot access /etc/rhsm/ca/redhat-uep.pem: No such file or directory
```
Assim que terminar o update do s.o faco um novo teste.

**Comment by davivcgarcia** [comment]
Validei em uma máquina de testes e esse problema está relacionado a [um bug no CentOS 7](https://bugs.centos.org/view.php?id=14785).

Como workaround vamos obter o certificado manualmente e coloca-lo no local que o Docker daemon busca. Para isso, execute como **root:**

```
openssl s_client -showcerts -servername registry.access.redhat.com -connect registry.access.redhat.com:443 </dev/null 2>/dev/null | openssl x509 -text > /etc/rhsm/ca/redhat-uep.pem
```

Você está acessando o material pelo link https://redhatbsb.gitbook.io/workshop-openshift ?

**Comment by davivcgarcia** [comment]
Você está acessando o material pelo link https://redhatbsb.gitbook.io/workshop-openshift ?

**Comment by davivcgarcia** [comment]
@glaucioguerra confirmou que os problemas foram sanados na versão `v3.11` material.
