### ISSUE TITLE
Ajuste no comando docker run (subida do wordpress)

### ISSUE THREAD

**Issue by glaucioguerra** [redhat-sa-brazil/workshop-openshift#56]
Pessoal,

Na execução do comando abaixo a ordem da porta está invertida:
```
docker run --rm -p 80:8080 wordpress
```
Consegui abrir somente com a ordem das portas 8080 (lado do host) e 80 lado do container:
```
docker run --rm -p 8080:80 wordpress
```

**Comment by davivcgarcia** [comment]
Você está correto (e não sei como isso não foi reportado antes). Consegue enviar em qual parte do documento você encontrou esse problema?

**Comment by davivcgarcia** [comment]
Você está acessando o material pelo link https://redhatbsb.gitbook.io/workshop-openshift ?

**Comment by davivcgarcia** [comment]
@glaucioguerra confirmou que os problemas foram sanados na versão `v3.11` material.
