### ISSUE TITLE
Avaliar se com o OC cluster up já nao é possivel fazer boa parte das tarefas

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-sa-brazil/workshop-openshift#7]

**Comment by rafaeltuelho** [comment]
Hum...
Eu, particularmente, não curto essa opção. Mas gostaria de ouvir o que acham...

`oc cluster app` não tem metrics e nem logging que funcione bem...

**Comment by luszczynski** [comment]
Eu acredito que tem vários labs que podem ser executados no cluster up e ainda vão aliviar um pouco o nosso cluster.
Já que as VMs que criamos para a parte 1 (docker) do workshop tem 4Gb de memória, acho que elas devem dar tranquilo para rodar o cluster up e executar os seguintes labs:

Lab 2.1.2 - Deploy imagem do Docker Hub
Lab
Lab
Lab
Lab
Lab
Lab
Lab
Lab

**Comment by luszczynski** [comment]
Eu acredito que tem vários labs que podem ser executados no cluster up e ainda vão aliviar um pouco o nosso cluster.
Já que as VMs que criamos para a parte 1 (docker) do workshop tem 4Gb de memória, acho que elas devem dar tranquilo para rodar o cluster up e executar os seguintes labs:

Lab 2.1.2 - Deploy imagem do Docker Hub
Lab 2.1.4 - Tolerância a falhas
Lab 2.1.5 - Deploy usando Source to Image (S2I)
Lab 2.1.6 - Usando Dockerfile
Lab 2.1.7 - Binary Deployment
Lab 2.1.8 - Health Checks
Lab 2.1.11 - Usando banco de dados
Lab 2.1.15 - Rollback
Lab 2.1.16 - Idle
Lab 2.1.17 - Image Stream
Lab 2.1.18 - ConfigMap e Secrets
Lab 2.2.1 - Canary Release
Lab 2.2.2 - Blue Green Deployment

Claro que precisamos testar como vai ser isso. Vou preparar o próximo workshop seguindo essa ideia e compartilho aqui se deu certo ou não.

**Comment by rafaeltuelho** [comment]
já estamos utilizando esse formato nos test drives atuais
