### ISSUE TITLE
Organizar a estrutura de diretórios e tópicos para o GitBook

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-sa-brazil/workshop-openshift#8]
Apesar de o conteúdo estar ótimo, a estrutura de tópicos está bem bagunçada. Precisamos seguir uma estrutura fácil de manter e com o mínimo de padronização.

**Comment by hodrigohamalho** [comment]
Isso é um pouco difícil, no início estavamos num formato um pouco menos normalizado com tópicos grandes e mais contínuo, eu segreguei em tópicos menores em um dos refactorings, teve gente que achou que ficou pior...

Temos que tentar achar o meio termo disso, mas não parece ser algo fácil de encontrar consenso.

**Comment by rafaeltuelho** [comment]
cara, a parte dois tá bem zuada. quando vc faz um clone do repo, tá complicado de se encontrar nos tópicos... Talvez seja o caso de usar uma estrutura menos rígida e favorecer a manutenabilidade...

**Comment by hodrigohamalho** [comment]
Foi o mesmo comentário do @davivcgarcia, vamos trabalhar nisso!

**Comment by luszczynski** [comment]
Acredito que devemos tirar essa parte de "Openshift para dev" e "Openshift para infra". Ou mudar a organição. A parte de dev tem muita coisa também de infra.
O que acham?

**Comment by hodrigohamalho** [comment]
Sim, por mim a gente deixava só separado por tópicos mesmo... Sem essas duas "hard divisions".
