### ISSUE TITLE
remover instruções de criação da VM (CentOS) na preparação

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-sa-brazil/workshop-openshift#9]
Creio que não precisamos dessa parte a partir de agora. O plano `A` é levar um OVA pronto e distribuir para os alunos. o plano `B` é disponibilizar uma VM no GCE ou AWS.

**Comment by luszczynski** [comment]
Algums alunos querem executar o lab depois em casa. Talvez eles possam aproveitar essa parte. O que acha @rafaeltuelho?

**Comment by rafaeltuelho** [comment]
@luszczynski eu disponibilizei um [`OVA`](https://drive.google.com/uc?id=16CHefCCaXL9wfhsx6C7jgH11ODO5mFdP&export=download) da VM no meu Drive para download público. O link para o aluno fazer o download  já está no roteiro de preparação.

**Comment by rafaeltuelho** [comment]
removi alguns intruções desnecessárias pra tornar o conteúdo mais objetivo
